# Generated by Django 5.2.6 on 2025-09-20 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Фото')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Производитель')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('actual', 'Актуальный'), ('bought', 'Купленный'), ('canceled', 'Отмененный')], default='actual', max_length=100, verbose_name='Статус')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('actual', 'Актуальный'), ('bought', 'Купленный'), ('canceled', 'Отмененный')], default='actual', max_length=100, verbose_name='Статус')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buyapp.product', verbose_name='Товар')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyapp.shoppinglist', verbose_name='Список')),
            ],
        ),
    ]
