# Generated by Django 5.2.6 on 2025-09-20 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkcart',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_cart_list', to='buyapp.shoppinglist', verbose_name='Список'),
        ),
    ]
